# port
server:
  port: 8888
  domain: http://10.224.81.70:8888
  servlet:
    session:
      cookie:
        name: WSSESSION
      timeout: 30m

# security
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ws-system
      clientSecret: Foxconn168!!
      accessTokenUri: http://10.224.81.70:8888/oauth-service/oauth/token
      userAuthorizationUri: http://10.224.81.70:8888/oauth-service/oauth/authorize
      clientAuthenticationScheme: header
    resource:
      userInfoUri: http://10.224.81.70:8888/oauth-service/user/me
      tokenInfoUri: http://10.224.81.70:8888/oauth-service/oauth/check_token
#    logoutUrl: http://10.224.81.70:8888/oauth-service/logout?redirectUrl=http://10.224.81.70:8888
    logoutUrl: http://10.224.81.70:8888/oauth-service/logout

# db
spring:
  datasource:
    url: jdbc:sqlserver://10.224.81.70:3000;databaseName=uthing
    username: 8170sql
    password: Foxconn123
    hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
#      minimumIdle: 3
#      maximumPoolSize: 5
#    hikari:
#      maximumPoolSize: 50
#      minimumIdle: 25
  jpa:
    show-sql: true
#    properties.hibernate.format_sql: true
    properties.hibernate.use_nationalized_character_data: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jmx:
    default-domain: ws
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      enabled: true
      max-file-size: 16MB
      max-request-size: 32MB

# cron
batch:
  cron:
    sync-data: 0 9/10 * * * *
    sync-cpk: 45 0/30 * * * *
    sync-daily: 0 30 11 * * *
    check-warning: 0 5/10 * * * *
    outdated-tracking: 0 35 7,19 * * *
    check-maintain-schedule: 0 30 7 * * *
    check-maintain-spec: 0 0/15 0 * * *
    sync-hourly: 30 45 * * * *
    sync-hr-meal: 0 0 9 * * *
    send-mail-hr-meal: 0 15 10 * * *
    sync-daily-remain-re: 0 30 7 * * *
    backup-hr-duty-data : 0 0 0 15 * *
    sync-daily-balance-re: 0 58 23 * * *
  fixed:
    check-locked: 30000
    check-notify-auto: 300000
    tracking: 60000
    notify-message: 60000
    hr-card-history: 3600000
    re-card-checkin: 3600000
  initial:
    check-locked: 54000
    check-notify-auto: 54000
    tracking: 108000
    notify-message: 72000
    hr-card-history: 3600000
    re-card-checkin: 1800000

b04:
  datasource:
    url: jdbc:sqlserver://10.224.69.103;databaseName=dbB04_Test;sendStringParametersAsUnicode=false
    username: oper
    password: wireless
    hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

b04wip:
  datasource:
    url: jdbc:sqlserver://10.224.81.17;databaseName=FOXCONNVNTE;sendStringParametersAsUnicode=false
    username: oper
    password: Foxconn168@@
    hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

b04ds02:
  datasource:
    url: jdbc:mysql://10.224.84.141/my_site
    username: landis
    password: test123
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

b05:
  datasource:
    url: jdbc:sqlserver://10.224.81.92;databaseName=B05_FII;sendStringParametersAsUnicode=false
    username: b05fii
    password: Foxconn168#
    hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

b06:
  datasource:
    url: jdbc:oracle:thin:@10.224.92.184:1521:orcl
    username: te
    password: tecft
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

b06ds02:
  datasource:
    url: jdbc:oracle:thin:@10.224.69.108:1521:orcl
    username: tea02
    password: tea02168
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

b06ds03:
  datasource:
    url: jdbc:oracle:thin:@10.224.92.188:1521:orcl
    username: re
    password: repro
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

b06te:
  datasource:
    url: jdbc:oracle:thin:@10.224.92.170:1521:ORCL
    username: tea02
    password: tea02168
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

nbbsfc:
  datasource:
    #    url: jdbc:oracle:thin:@10.239.89.252:1521:vnsfc
    url: jdbc:oracle:thin:@10.225.35.11:1521:vnsfc
    username: nbbyr
    password: nbbyr19
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

nbbap:
  datasource:
    #    url: jdbc:oracle:thin:@10.239.89.251:1521:vnap
    url: jdbc:oracle:thin:@10.225.35.9:1521:vnap
    username: qreport
    password: dellselect0406!
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

nbbtefii:
  datasource:
#    url: jdbc:oracle:thin:@10.239.89.223:1521:ORCL
    url: jdbc:oracle:thin:@10.225.35.69:1521:ORCL
    username: TE_NBB_FII
    password: TE_NBB_FII
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

qcsfc:
  datasource:
    url: jdbc:oracle:thin:@10.221.24.93:1527:sfcodb
    username: hogan
    password: sfsselect
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

c03sfc:
  datasource:
    url: jdbc:oracle:thin:@10.224.134.99:1527:sfcodb
    username: tableau
    password: tableau2019#!
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

b06sfc:
  datasource:
    url: jdbc:oracle:thin:@10.224.92.136:1527:vnsfc
    username: tableau
    password: tableau2019#!
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

b04sfc:
  datasource:
    url: jdbc:oracle:thin:@10.224.81.33:1521:vnsfc
    username: CQYR
    password: cqyieldrate
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 3
      maximumPoolSize: 5

# uploading
path:
  data: D:/tiennd/data/project/ws/
  autoit-sap: D:/tiennd/app/sap/bin/
  phantomjs: D:/tiennd/app/phantomjs/bin/
  highcharts-export: D:/tiennd/app/phantomjs/highcharts/

# logging
logging:
  path: logs/ws
  level:
    com.foxconn.fii: INFO
#    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    com.zaxxer.hikari: DEBUG